version: 2.1
orbs:
  codecov: codecov/codecov@1.0.1
working_directory: ~/CryptoCalculatorService
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4  # primary container for this build
      - image: circleci/mongo:4.2.3
      - image: spotify/kafka
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python setup_dev_user.py
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export FLASK_ENV=development'
      - run:
          name: Wait for Mongo to start
          command: dockerize -wait tcp://127.0.0.1:27017 -timeout 120s
      - run:
          name:  install mongo clients
          command: |
              sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
              echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
              sudo apt-get update
              apt-get update && apt-get -y install apt-transport-https curl
              sudo apt-get install -y mongodb-org-shell

      - run:
          name: Configure MongoDB
          command: |
            mongo admin --eval 'db.addUser( { user: "admin", pwd: "admin", roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] } )'
            mongo test -u admin -p admin --authenticationDatabase admin --eval 'db.addUser({ user: "test", pwd: "test", roles: [{ role: "dbOwner", db: "CryptoCalculatorService" }]})'
      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate
            py.test -vv CryptoCalculatorService/tests
      - run:
          name: Code coverage
          command: |
             . venv/bin/activate
             py.test --cov=CryptoCalculatorService